### PR TITLE
Support hv_product! for TwiceDifferentiable

### PR DESCRIPTION
**Pull request by timholy**
The motivation was to be able to use `Optim.KrylovTrustRegion` on CUTEst models. (There will be a separate Optim PR after this gets tagged in a new release.)

### CODE REVIEW

**Comment by timholy** [comment]
In case it's useful for evaluation, here's the diff in Optim:
```diff
diff --git a/src/multivariate/solvers/second_order/krylov_trust_region.jl b/src/multivariate/solvers/second_order/krylov_trust_region.jl
index 355bd907..60f03656 100644
--- a/src/multivariate/solvers/second_order/krylov_trust_region.jl
+++ b/src/multivariate/solvers/second_order/krylov_trust_region.jl
@@ -89,11 +89,11 @@ function trace!(tr, d, state, iteration, method::KrylovTrustRegion, options, cur
 end
 
 
-function cg_steihaug!(objective::TwiceDifferentiableHV,
+function cg_steihaug!(objective,
                       state::KrylovTrustRegionState{T},
                       method::KrylovTrustRegion) where T
     n = length(state.x)
-    x, g, d, r, z, Hd = state.x, gradient(objective), state.d, state.r, state.s, hv_product(objective)
+    x, g, d, r, z = state.x, gradient(objective), state.d, state.r, state.s
 
     fill!(z, 0.0)  # the search direction is initialized to the 0 vector,
     r .= g  # so at first the whole gradient is the residual.
@@ -103,7 +103,7 @@ function cg_steihaug!(objective::TwiceDifferentiableHV,
     state.cg_iters = 0
     for i in 1:n
         state.cg_iters += 1
-        hv_product!(objective, x, d)
+        Hd = hv_product!(objective, x, d)
         dHd = dot(d, Hd)
         if -1e-15 < dHd < 1e-15
             break
@@ -135,12 +135,12 @@ function cg_steihaug!(objective::TwiceDifferentiableHV,
         end
     end
 
-    hv_product!(objective, x, z)
+    Hd = hv_product!(objective, x, z)
     return dot(g, z) + 0.5 * dot(z, Hd)
 end
 
 
-function update_state!(objective::TwiceDifferentiableHV,
+function update_state!(objective,
                           state::KrylovTrustRegionState,
                           method::KrylovTrustRegion)
     state.m_diff = cg_steihaug!(objective, state, method)
diff --git a/test/multivariate/solvers/second_order/krylov_trust_region.jl b/test/multivariate/solvers/second_order/krylov_trust_region.jl
index ea8d1ea1..4bdb32cd 100644
--- a/test/multivariate/solvers/second_order/krylov_trust_region.jl
+++ b/test/multivariate/solvers/second_order/krylov_trust_region.jl
@@ -6,19 +6,35 @@
         (x[1] - 5.0)^4
     end
 
-    function fg!(storage::Vector, x::Vector)
+    function g!(storage, x)
         storage[1] = 4.0 * (x[1] - 5.0)^3
+        return storage
+    end
+
+    function fg!(storage::Vector, x::Vector)
+        g!(storage, x)
         f(x)
     end
 
     function hv!(storage::Vector, x::Vector, v::Vector)
         storage[1] = 12.0 * (x[1] - 5.0)^2 * v[1]
+        return storage
+    end
+
+    function h!(storage::AbstractMatrix, x)
+        storage[1,1] = 12.0 * (x[1] - 5.0)^2
+        return storage
     end
 
     d = Optim.TwiceDifferentiableHV(f, fg!, hv!, [0.0])
 
     result = Optim.optimize(d, [0.0], Optim.KrylovTrustRegion())
     @test norm(Optim.minimizer(result) - [5.0]) < 0.01
+
+    d = Optim.TwiceDifferentiable(f, g!, fg!, h!, [0.0])
+
+    result = Optim.optimize(d, [0.0], Optim.KrylovTrustRegion())
+    @test norm(Optim.minimizer(result) - [5.0]) < 0.01
 end
 
 @testset "Toy test problem 2" begin
(END)
```

**Comment by timholy** [comment]
Bump. I can't merge this on my own.

**Comment by pkofod** [comment]
Hi @timholy ! I don't know why but I did not get a notification for this? Anyway, looks good.

**Comment by timholy** [comment]
Thanks! Can we get a new release? Tests on changes to Optim won't pass without one.

**Comment by pkofod** [comment]
Yes!

**Pull request merged**
