### PR TITLE
Add `value(d, x)` for multivalued objective

### PR DESCRIPTION
**Pull request by iewaij**
This PR add `value(d, x)` method for multivalued objective.

### CODE REVIEW

**Comment by pkofod** [comment]
Was it only defined for `F<:Number` before?

**Comment by iewaij** [comment]
Yes I think so.

**Comment by pkofod** [comment]
I agree with the addition of the method, but what are the tests supposed to test? You should add a test of the `value(obj, F, x)` form instead. I don't understand why you're testing `value(nd, x_alt)` as this has nothing to do with this PR. Was it just to be sure that it didn't only work for `x_seed`? You can keep the tests here, but you need to add something of the form described above.

**Comment by iewaij** [comment]
It's defined in the same form as `value!!(obj::AbstractObjective, F, x)` in line `176`. For a multi-valued objective, `value(nd, x_alt)` called the function `value(nd, copy(nd.F), x_alt)` using multiple dispatch in line `166`. The reason to include `value(nd, x_alt)` is that `value(nd, x_seed)` in the test doesn't test `obj.f(F, x)` because `x_seed == obj.x_f`. Hope this could clarify.

**Pull request merged**
