### PR TITLE
 Rethrow error in hessian check if it's not a BoundsError or MethodEr…

### PR DESCRIPTION
**Pull request by pkofod**
…ror. ref: https://github.com/JuliaNLSolvers/NLSolversBase.jl/pull/6#discussion_r110874565

### CODE REVIEW

**Comment by tkelman** [comment]
did you plan to amend the tag for this or not worth worrying about?

**Comment by pkofod** [comment]
> did you plan to amend the tag for this or not worth worrying about?

I sorta planned to push a patch x.y.1, but if I can get you to close the existing PR from attobot, I'll just open a new one, so there's only one version in METADATA with these changes.

**Comment by tkelman** [comment]
Do you want to use the same version number or just go to 2.1.1 and not publish 2.1.0?

**Comment by pkofod** [comment]
> Do you want to use the same version number or just go to 2.1.1 and not publish 2.1.0?

2.1.1 and then 2.1.0 just lives in the git repo, not METADATA.

**Pull request merged**
