### PR TITLE
Introduce Constraints objects

### PR DESCRIPTION
**Pull request by anriseth**
This needs 
- [x] Tests (may be some in `IPNewtons` we can use?)
- [x] A review to check whether all the code I put here is necessary

As a future PR, we should introduce `value!` et al. to the `NDifferentiableConstraints` objects as well. But let's deal with that after we have moved IPNewton into Optim.
- [x] Add Issue on `value!` et al. for Constraints

### CODE REVIEW

**Comment by anriseth** [comment]
This is ready to go. Can someone review the changes, please?

**Comment by pkofod** [comment]
Looks good. I'm wondering if we should simply use the existing NDifferentiable setup for the constraints, and have the constraints be a wrapper around an NDifferentiable and ConstraintsBounds? Would buy us AD, counters, etc automatically. We can always iterate on this in the future...

**Comment by anriseth** [comment]
> Looks good. I'm wondering if we should simply use the existing NDifferentiable setup for the constraints, and have the constraints be a wrapper around an NDifferentiable and ConstraintsBounds? Would buy us AD, counters, etc automatically. We can always iterate on this in the future...

Yes, if that's possible it will be very useful :)

**Comment by pkofod** [comment]
I don't see why it wouldn't? Currently a constraint is simply a function and it's derivative + it's bounds. What I suggest is basically

```julia
struct Constraints{Td, Tb}
    c::Td
    b::Tb
end
```
where `c` is then either a `NonDifferentiable`, a `OnceDifferentiable` or a `TwiceDifferentiable`. This seems much simpler than "duplicating" these types with a `Constraints` suffix. 

I know where this comes from, I just figured I'd metion it.

**Comment by pkofod** [comment]
another relevant thing is to consider things like restricting parameters to a Ball for example. In https://github.com/cortner/ConstrainedOptim.jl we had a BallConstraint type used to project back into the ball.

**Comment by anriseth** [comment]
Great, it seems like we can quickly improve the current interface then :+1: 

Ah, and BallConstraint projection works better than supplying a constraint `c(x) = sum(abs2, x)` with `c(x) \leq C` ?

**Comment by pkofod** [comment]
> Ah, and BallConstraint projection works better than supplying a constraint c(x) = sum(abs2, x) with c(x) \leq C ?

I guess it can be simpler in some cases, but "better" is sort of a multivalued thing here.

**Comment by longemen3000** [comment]
adding to this, one problem is the existence of the second order differenciable constraints, because that hessian is not of any NDifferentiable type. as my current understanding

**Pull request merged**
