### PR TITLE
Add convert for ConstraintBounds

### PR DESCRIPTION
**Pull request by anriseth**

### CODE REVIEW

**Comment by pkofod** [comment]
What's the use-case?

**Comment by anriseth** [comment]
If I supply empty constraints using `lx=[]; ux=[]` to IPNewton, then `ConstraintBounds` gets the eltype `Union{}`, which does not work. I started trying to fix this, but then I realised that it requires other changes in the interface to fix the underlying problem as well. So I'm not sure if it's worth doing, however, it may be useful for something in future?

It is also solved by using `lx = Float64[]`, for example.

**Comment by pkofod** [comment]
Yup, that's mentioned in the comments. You will get type-unstable code unless you provide something like `Float64[]` as you mentioned. We can add this.

**Comment by pkofod** [comment]
ref https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/c62b4d18668d9abb870af08700f9a58d175b4eb8/src/objective_types/constraints.jl#L151

**Pull request merged**
